org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Opt out of AGP 9 new DSL ? required while Flutter plugin uses Groovy DSL
android.newDsl=false

# Disable built-in Kotlin to avoid version conflicts with flutter-gradle-plugin
android.builtInKotlin=false
systemProp.https.protocols=TLSv1.2,TLSv1.3
kotlin.incremental=false
kotlin.incremental.multiproject=false